version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: kalpee-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kalpee_db
      MYSQL_USER: kalpee_user
      MYSQL_PASSWORD: "167907"
      MYSQL_ROOT_PASSWORD: "167907"
    ports:
      - "3306:3306"
    volumes:
      - kalpee_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kalpee_user", "-p167907"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  kalpee_mysql_data:
